name: Spankbang API test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at 00:00 UTC

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest bs4 git+https://github.com/EchterAlsFake/eaf_base_api
    - name: Test with pytest
      run: |
        pytest